### ISSUE TITLE
Sql Error

### ISSUE THREAD

**Issue by r3comp1le** [ciscocsirt/malspider#16]
Fresh install and 1st attempt to hit Dashboard

```
Exception Value:	
(1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'malspider.alert.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")

Exception Location:	/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py in defaulterrorhandler, line 36
```

**Comment by jasheppa5** [comment]
I wasn't able to reproduce this with a fresh install of Ubuntu, but I think
I know how to fix it. Based on the error message it has something to do
with your mysql configuration and the GROUP BY query used to aggregate the
alert count.

Before I push code, do you mind making a quick one line change?:

In /home/malspider/malspider/malspider_django/dashboard/functions/model_helper.py
go to line 61 and replace the old sql statement with:

sql = """Select count(*),reason,org_id from alert GROUP BY reason, org_id"""
;
I believe your more strict mysql setup is complaining about me not
selecting the columns in the group by. If it works for you i'll push the
code since this should work on less strict configurations as well.

Thanks,
James

**Comment by r3comp1le** [comment]
Thanks your recent commit fixed it!

**Comment by jasheppa5** [comment]
Hmm ok... So you didn't need to update the sql statement? I pushed a
changed earlier today to speed up page performance and the error message
seemed related.

-James

**Comment by r3comp1le** [comment]
No, I just used the new model_helper.py file and it loaded the Dashboard

**Comment by jasheppa5** [comment]
I was able to reproduce the error when I update the sql mode to
"only_full_group_by". The best fix seems to be removing that from the sql
mode:

set GLOBAL sql_mode = ''";

I can't include "id" in the group by without messing up the alert
aggregation :-(

**Comment by r3comp1le** [comment]
place that in the model_helper.py?

**Comment by jasheppa5** [comment]
SSH to your Malspider box and at the terminal type:

mysql -u root -p

Type your mysql root password and you should be presented with a mysql
prompt, then type this to remove the strict group_by setting:

mysql> set GLOBAL sql_mode = '';



Just curious, what version of mysql did you install?

**Comment by r3comp1le** [comment]
5.7.16-0ubuntu0.14.04.1
